# Generated by Django 3.2.15 on 2022-09-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcf_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='IDENTITY',
            new_name='ID_vcf',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
